export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const DELETE_CARD = 'DELETE_CARD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
